"""
Bandit simulation utilities for testing coverage of anytime-valid confidence
sequences.

Reference: Luedtke & Soni (2024), "Anytime-Valid Off-Policy Inference for
Contextual Bandits" — Algorithm 1.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import numpy as np
import pandas as pd
from plotnine import (
    aes,
    geom_hline,
    geom_line,
    geom_ribbon,
    ggplot,
    labs,
    scale_color_manual,
    scale_fill_manual,
    theme_bw,
)

from .pseudo_outcomes import dr_pseudo_outcomes, importance_weights, iw_pseudo_outcomes
from .reward_predictors import OLSRewardPredictor, RewardPredictor


@dataclass
class BanditData:
    """Data generated by a contextual bandit simulation.

    Attributes
    ----------
    contexts : np.ndarray, shape (T, d) or (T,)
        Observed contexts X_t.
    actions : np.ndarray, shape (T,)
        Actions A_t chosen by the logging policy.
    rewards : np.ndarray, shape (T,)
        Observed rewards R_t ∈ [0, 1].
    log_probs : np.ndarray, shape (T,)
        Logging policy probabilities h_t(A_t|X_t).
    target_probs : np.ndarray, shape (T,)
        Target policy probabilities π(A_t|X_t).
    weights : np.ndarray, shape (T,)
        Importance weights w_t = π(A_t|X_t) / h_t(A_t|X_t).
    true_policy_value : float
        True policy value ν = E_π[R], known analytically.
    """

    contexts: np.ndarray
    actions: np.ndarray
    rewards: np.ndarray
    log_probs: np.ndarray
    target_probs: np.ndarray
    weights: np.ndarray
    true_policy_value: float


class BanditSimulator:
    """Simulate contextual bandit data and compute pseudo-outcomes.

    Implements data generation per Algorithm 1 in Luedtke & Soni (2024).

    Parameters
    ----------
    logging_policy : Callable
        Function ``(contexts, actions) -> probs`` giving h_t(A_t|X_t).
    target_policy : Callable
        Function ``(contexts, actions) -> probs`` giving π(A_t|X_t).
    reward_fn : Callable
        Function ``(contexts, actions) -> rewards`` in [0, 1].
    context_fn : Callable
        Function ``(T: int) -> contexts`` array.
    actions : np.ndarray
        All possible actions.
    true_policy_value : float
        ν = E_π[R], provided analytically by the caller.
    reward_predictor : RewardPredictor, Callable, or None
        Reward model for DR pseudo-outcomes.

        - ``None`` (default): an :class:`OLSRewardPredictor` is created
          automatically each time DR pseudo-outcomes are requested.
        - :class:`RewardPredictor` instance: ``fit`` is called on the observed
          data before each pseudo-outcome computation; ``predict`` is called in
          batch for efficiency.
        - Plain ``Callable`` ``(ctx, act) -> preds``: called per time-step for
          backward compatibility.

        Any sklearn regressor can be used via :class:`SklearnRewardPredictor`.
    k : float
        Truncation parameter k ≥ 0.
    rng : np.random.Generator or None
        Random number generator for reproducibility.
    """

    def __init__(
        self,
        logging_policy: Callable,
        target_policy: Callable,
        reward_fn: Callable,
        context_fn: Callable,
        actions: np.ndarray,
        true_policy_value: float,
        reward_predictor: RewardPredictor | Callable | None = None,
        k: float = 0.0,
        rng: np.random.Generator | None = None,
    ):
        self.logging_policy = logging_policy
        self.target_policy = target_policy
        self.reward_fn = reward_fn
        self.context_fn = context_fn
        self.actions = np.asarray(actions)
        self.true_policy_value = true_policy_value
        self.reward_predictor = reward_predictor
        self.k = k
        self.rng = rng if rng is not None else np.random.default_rng()

    def simulate(self, T: int) -> BanditData:
        """Generate T steps of bandit data.

        Follows Algorithm 1: sample context, select action via logging policy,
        observe reward.

        Parameters
        ----------
        T : int
            Number of time steps.

        Returns
        -------
        BanditData
        """
        contexts = self.context_fn(T)

        n_actions = len(self.actions)
        action_indices = np.zeros(T, dtype=int)
        log_probs = np.zeros(T)

        for t in range(T):
            ctx = contexts[t : t + 1] if contexts.ndim > 1 else contexts[t : t + 1]
            probs = np.array(
                [float(self.logging_policy(ctx, np.array([a]))[0]) for a in self.actions]
            )
            probs = probs / probs.sum()
            idx = self.rng.choice(n_actions, p=probs)
            action_indices[t] = idx
            log_probs[t] = probs[idx]

        actions = self.actions[action_indices]
        rewards = self.reward_fn(contexts, actions)

        target_probs = np.array([
            float(self.target_policy(
                contexts[t : t + 1] if contexts.ndim > 1 else contexts[t : t + 1],
                np.array([actions[t]])
            )[0])
            for t in range(T)
        ])

        weights = importance_weights(target_probs, log_probs)

        return BanditData(
            contexts=contexts,
            actions=actions,
            rewards=rewards,
            log_probs=log_probs,
            target_probs=target_probs,
            weights=weights,
            true_policy_value=self.true_policy_value,
        )

    def pseudo_outcomes(
        self, data: BanditData, kind: str = "dr"
    ) -> tuple[np.ndarray, np.ndarray]:
        """Compute pseudo-outcomes from bandit data.

        For ``kind="dr"`` with a :class:`RewardPredictor` (or the default OLS),
        the predictor is fit on the full observed data then used to compute
        truncated doubly-robust pseudo-outcomes in batch.

        Parameters
        ----------
        data : BanditData
        kind : str
            ``"iw"`` for importance-weighted, ``"dr"`` for doubly-robust.

        Returns
        -------
        phi_lower : np.ndarray, shape (T,)
        phi_upper : np.ndarray, shape (T,)
        """
        if kind == "iw":
            return iw_pseudo_outcomes(data.rewards, data.weights)

        if kind == "dr":
            predictor = self.reward_predictor
            if predictor is None:
                predictor = OLSRewardPredictor(self.actions)

            if isinstance(predictor, RewardPredictor):
                return self._dr_with_sklearn(data, predictor)
            else:
                return self._dr_with_callable(data, predictor)

        raise ValueError(f"Unknown kind {kind!r}. Use 'iw' or 'dr'.")

    def evaluate_policy(
        self,
        data: BanditData,
        target_policy: Callable,
        kind: str = "dr",
        reward_predictor: "RewardPredictor | Callable | None" = None,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Evaluate an arbitrary target policy offline on existing bandit data.

        Enables evaluating multiple target policies on the *same* logged data
        without re-simulating.  A single fitted reward model can be shared
        across all policies to avoid redundant fitting:

        .. code-block:: python

            predictor = OLSRewardPredictor(actions)
            predictor.fit(data.contexts, data.actions, data.rewards)

            phi_l1, phi_u1 = sim.evaluate_policy(data, pi_1, reward_predictor=predictor)
            phi_l2, phi_u2 = sim.evaluate_policy(data, pi_2, reward_predictor=predictor)

        Parameters
        ----------
        data : BanditData
            Logged data collected under the logging policy.
        target_policy : Callable
            ``(contexts, actions) -> probs`` giving π(A_t|X_t).  Called in
            batch over the full context/action arrays.
        kind : str
            ``"iw"`` for importance-weighted or ``"dr"`` for doubly-robust.
        reward_predictor : RewardPredictor, Callable, or None
            Reward model for DR pseudo-outcomes.

            - ``None``: a fresh :class:`OLSRewardPredictor` is fitted on
              ``data`` automatically.
            - :class:`RewardPredictor` already fitted (``_fitted=True``): used
              as-is — allows sharing one model across multiple policy evals.
            - Unfitted :class:`RewardPredictor`: fitted on ``data`` in-place.
            - Plain ``Callable``: called per time-step (legacy path).

        Returns
        -------
        phi_lower : np.ndarray, shape (T,)
        phi_upper : np.ndarray, shape (T,)
        """
        if kind == "iw":
            target_probs = target_policy(data.contexts, data.actions)
            weights = importance_weights(
                np.asarray(target_probs), data.log_probs
            )
            return iw_pseudo_outcomes(data.rewards, weights)

        if kind == "dr":
            predictor = reward_predictor
            if predictor is None:
                predictor = OLSRewardPredictor(self.actions)

            if isinstance(predictor, RewardPredictor):
                if not predictor._fitted:
                    predictor.fit(data.contexts, data.actions, data.rewards)
                return self._dr_from_fitted_predictor(data, target_policy, predictor)
            else:
                return self._dr_with_callable(data, predictor, target_policy)

        raise ValueError(f"Unknown kind {kind!r}. Use 'iw' or 'dr'.")

    def _dr_with_sklearn(
        self, data: BanditData, predictor: RewardPredictor
    ) -> tuple[np.ndarray, np.ndarray]:
        """DR pseudo-outcomes using a RewardPredictor — vectorized batch calls."""
        predictor.fit(data.contexts, data.actions, data.rewards)
        return self._dr_from_fitted_predictor(data, self.target_policy, predictor)

    def _dr_from_fitted_predictor(
        self,
        data: BanditData,
        target_policy: Callable,
        predictor: RewardPredictor,
    ) -> tuple[np.ndarray, np.ndarray]:
        """DR pseudo-outcomes given an already-fitted predictor and target policy.

        Importance weights for the observed (X_t, A_t) use the given
        ``target_policy``.  The expectation over π in the DR correction uses
        *action-specific* thresholds k/w_a where w_a = π(a|X_t)/h(a|X_t) for
        each hypothetical action a — this is required for the estimator to be
        unbiased when target_policy ≠ logging_policy.
        """
        T = len(data.rewards)
        k = self.k

        # Importance weights at observed (X_t, A_t)
        target_probs = target_policy(data.contexts, data.actions)
        weights = importance_weights(np.asarray(target_probs), data.log_probs)
        safe_weights = np.where(weights > 0, weights, 1.0)
        obs_threshold = k / safe_weights   # used in w_t*(R_t - min(r̂_t, k/w_t))

        r_hat = predictor.predict(data.contexts, data.actions)

        r_hat_pi_mean_lower = np.zeros(T)
        r_hat_pi_mean_upper = np.zeros(T)

        for a in self.actions:
            actions_a = np.full(T, a)
            r_hat_a = predictor.predict(data.contexts, actions_a)       # (T,)
            pi_a    = np.asarray(target_policy(data.contexts, actions_a))  # π(a|X_t)
            h_a     = np.asarray(self.logging_policy(data.contexts, actions_a))  # h(a|X_t)

            # Action-specific importance weight w_a = π(a|X_t)/h(a|X_t)
            safe_h_a = np.where(h_a > 0, h_a, 1.0)
            w_a      = pi_a / safe_h_a
            safe_w_a = np.where(w_a > 0, w_a, 1.0)
            threshold_a = k / safe_w_a  # k / w_a for each action a

            r_hat_pi_mean_lower += pi_a * np.minimum(r_hat_a, threshold_a)
            r_hat_pi_mean_upper += pi_a * np.minimum(1.0 - r_hat_a, threshold_a)

        return dr_pseudo_outcomes(
            data.rewards, weights, r_hat,
            r_hat_pi_mean_lower, r_hat_pi_mean_upper, k,
        )

    def _dr_with_callable(
        self,
        data: BanditData,
        reward_predictor: Callable,
        target_policy: Callable | None = None,
    ) -> tuple[np.ndarray, np.ndarray]:
        """DR pseudo-outcomes using a plain callable — per-step calls."""
        policy = target_policy if target_policy is not None else self.target_policy
        T = len(data.rewards)
        contexts = data.contexts
        k = self.k

        # Recompute weights for this target policy
        target_probs_all = policy(contexts, data.actions)
        weights = importance_weights(np.asarray(target_probs_all), data.log_probs)

        r_hat = np.array([
            float(reward_predictor(
                contexts[t : t + 1] if contexts.ndim > 1 else contexts[t : t + 1],
                np.array([data.actions[t]])
            )[0])
            for t in range(T)
        ])

        r_hat_pi_mean_lower = np.zeros(T)
        r_hat_pi_mean_upper = np.zeros(T)
        for t in range(T):
            ctx_t = contexts[t : t + 1] if contexts.ndim > 1 else contexts[t : t + 1]
            for a in self.actions:
                pi_a = float(policy(ctx_t, np.array([a]))[0])
                h_a  = float(self.logging_policy(ctx_t, np.array([a]))[0])
                # Action-specific threshold k/w_a where w_a = π(a|X)/h(a|X)
                w_a = pi_a / h_a if h_a > 0 else np.inf
                threshold_a = k / w_a if w_a > 0 else 0.0
                r_hat_a = float(reward_predictor(ctx_t, np.array([a]))[0])
                r_hat_pi_mean_lower[t] += pi_a * min(r_hat_a, threshold_a)
                r_hat_pi_mean_upper[t] += pi_a * min(1.0 - r_hat_a, threshold_a)

        return dr_pseudo_outcomes(
            data.rewards, weights, r_hat,
            r_hat_pi_mean_lower, r_hat_pi_mean_upper, k,
        )

    def coverage_experiment(
        self,
        T: int,
        n_trials: int,
        cs_factory: Callable,
        alpha: float = 0.1,
        kind: str = "dr",
    ) -> dict:
        """Run a coverage experiment over multiple trials.

        Checks P(∀t, ν ∈ [L_t, U_t]) ≥ 1 - α.

        Parameters
        ----------
        T : int
            Number of time steps per trial.
        n_trials : int
            Number of independent trials.
        cs_factory : Callable
            ``alpha -> ConfidenceSequence`` instance (with ``.bounds()`` method).
        alpha : float
            Significance level.
        kind : str
            Pseudo-outcome type (``"iw"`` or ``"dr"``).

        Returns
        -------
        dict with keys:
            coverage_rate : float
                Fraction of trials where ν is covered for all t.
            lower_bounds : np.ndarray, shape (n_trials, T)
            upper_bounds : np.ndarray, shape (n_trials, T)
            true_value : float
        """
        cs = cs_factory(alpha)
        lower_bounds = np.zeros((n_trials, T))
        upper_bounds = np.zeros((n_trials, T))
        nu = self.true_policy_value

        for trial in range(n_trials):
            data = self.simulate(T)
            phi_l, phi_u = self.pseudo_outcomes(data, kind=kind)
            lower_bounds[trial], upper_bounds[trial] = cs.bounds(phi_l, phi_u)

        covered = np.all((lower_bounds <= nu) & (upper_bounds >= nu), axis=1)
        coverage_rate = float(covered.mean())

        return {
            "coverage_rate": coverage_rate,
            "lower_bounds": lower_bounds,
            "upper_bounds": upper_bounds,
            "true_value": nu,
        }

    def plot_bounds(
        self,
        lower: np.ndarray,
        upper: np.ndarray,
        title: str = "",
        true_value: float | None = None,
    ):
        """Plot a single-trial confidence sequence against the true policy value.

        The shaded ribbon shows [L_t, U_t] over time; the dashed line marks the
        true policy value ν.

        Parameters
        ----------
        lower : np.ndarray, shape (T,)
            Lower confidence bound sequence L_t.
        upper : np.ndarray, shape (T,)
            Upper confidence bound sequence U_t.
        title : str
            Plot title.  Defaults to "Confidence Sequence".
        true_value : float or None
            True policy value ν to mark with a dashed line.  Defaults to
            ``self.true_policy_value``.

        Returns
        -------
        plotnine.ggplot
        """
        lower = np.asarray(lower)
        upper = np.asarray(upper)
        T = len(lower)
        nu = true_value if true_value is not None else self.true_policy_value

        df = pd.DataFrame({
            "t": np.arange(1, T + 1),
            "lower": lower,
            "upper": upper,
        })

        return (
            ggplot(df, aes(x="t"))
            + geom_ribbon(aes(ymin="lower", ymax="upper"), fill="#4393c3", alpha=0.4)
            + geom_line(aes(y="lower"), color="#2166ac", size=0.6)
            + geom_line(aes(y="upper"), color="#2166ac", size=0.6)
            + geom_hline(
                yintercept=nu,
                linetype="dashed",
                color="#d6604d",
                size=0.9,
            )
            + labs(
                x="Time step t",
                y="Policy value",
                title=title or "Confidence Sequence",
            )
            + theme_bw()
        )

    def plot_coverage(
        self,
        result: dict,
        title: str = "",
        max_trials: int = 50,
        rng: np.random.Generator | None = None,
    ):
        """Plot confidence sequences from a coverage experiment.

        Draws up to ``max_trials`` confidence bands as ribbons, coloured by
        whether they achieve simultaneous coverage of ν.  The true policy value
        is shown as a dashed line.

        Parameters
        ----------
        result : dict
            Output of :meth:`coverage_experiment`.
        title : str
            Plot title.  Defaults to displaying the empirical coverage rate.
        max_trials : int
            Maximum number of trial bands to draw (randomly sampled when the
            total exceeds this).
        rng : np.random.Generator or None
            Controls random sampling of trials when ``max_trials < n_trials``.

        Returns
        -------
        plotnine.ggplot
        """
        lower_bounds = result["lower_bounds"]   # (n_trials, T)
        upper_bounds = result["upper_bounds"]   # (n_trials, T)
        nu = result["true_value"]
        coverage_rate = result["coverage_rate"]

        n_trials, T = lower_bounds.shape

        # Per-trial simultaneous coverage flag
        covered_mask = np.all(
            (lower_bounds <= nu) & (upper_bounds >= nu), axis=1
        )

        # Subsample trials for legibility
        _rng = rng if rng is not None else np.random.default_rng(0)
        if n_trials > max_trials:
            idx = _rng.choice(n_trials, size=max_trials, replace=False)
        else:
            idx = np.arange(n_trials)

        t_vals = np.arange(1, T + 1)
        rows = {
            "t": np.tile(t_vals, len(idx)),
            "lower": lower_bounds[idx].ravel(),
            "upper": upper_bounds[idx].ravel(),
            "trial": np.repeat(idx, T),
            "coverage": np.repeat(
                np.where(covered_mask[idx], "covered", "uncovered"), T
            ),
        }
        df = pd.DataFrame(rows)

        return (
            ggplot(df, aes(x="t", group="trial", fill="coverage", color="coverage"))
            + geom_ribbon(aes(ymin="lower", ymax="upper"), alpha=0.15, size=0)
            + geom_hline(
                yintercept=nu,
                linetype="dashed",
                color="black",
                size=1.0,
            )
            + scale_fill_manual(
                values={"covered": "#4393c3", "uncovered": "#d6604d"}
            )
            + scale_color_manual(
                values={"covered": "#4393c3", "uncovered": "#d6604d"}
            )
            + labs(
                x="Time step t",
                y="Policy value",
                fill="Trial",
                color="Trial",
                title=title or f"Coverage experiment  (empirical rate = {coverage_rate:.1%})",
            )
            + theme_bw()
        )
